CREATE TABLE properties (
  property_number TEXT,
  school_district TEXT,
  curr_owner TEXT,
  wetlands TEXT,
  nbhd_cd TEXT,
  address TEXT,
  site_no TEXT,
  acreage FLOAT,
  zoning TEXT,
  property_class TEXT,

  -- Assessment information
  av_land_2014 INTEGER,
  av_land_2013_fmv INTEGER,
  av_land_2013 INTEGER,
  av_total_2014 INTEGER,
  av_total_2013_fmv INTEGER,
  av_total_2013 INTEGER,

  taxable_village INTEGER,
  taxable_school INTEGER,
  taxable_county INTEGER, -- uh-oh
  taxable_county_solid_waste INTEGER, -- uh-oh
  taxable_bronx_sewer INTEGER,
  taxable_mamaroneck_sewer INTEGER,
  taxable_hutchinson_sewer INTEGER,
  taxable_ TEXT, -- uh-oh

  -- Structural information
  ap1 BOOLEAN,
  ap3 BOOLEAN,
  ap4 BOOLEAN,
  ap6 BOOLEAN,
  ap7 BOOLEAN,
  be1 BOOLEAN,
  be2 BOOLEAN,
  be4 BOOLEAN,
  be5 BOOLEAN,
  be6 BOOLEAN,
  bf1 BOOLEAN,
  cc1 BOOLEAN,
  cp5 BOOLEAN,
  cp6 BOOLEAN,
  cp7 BOOLEAN,
  el2 BOOLEAN,
  fb1 BOOLEAN,
  fb4 BOOLEAN,
  fb5 BOOLEAN,
  fb6 BOOLEAN,
  fb8 BOOLEAN,
  fc1 BOOLEAN,
  fc3 BOOLEAN,
  fc4 BOOLEAN,
  fc5 BOOLEAN,
  fc6 BOOLEAN,
  ft1 BOOLEAN,
  ft2 BOOLEAN,
  gb1 BOOLEAN,
  gc2 BOOLEAN,
  gc3 BOOLEAN,
  gh2 BOOLEAN,
  gh3 BOOLEAN,
  gh5 BOOLEAN,
  gn2 BOOLEAN,
  ld1 BOOLEAN,
  ld2 BOOLEAN,
  lp1 BOOLEAN,
  lp3 BOOLEAN,
  lp4 BOOLEAN,
  lp5 BOOLEAN,
  lp6 BOOLEAN,
  lp7 BOOLEAN,
  lp8 BOOLEAN,
  lp9 BOOLEAN,
  lr1 BOOLEAN,
  lr2 BOOLEAN,
  lr3 BOOLEAN,
  ls1 BOOLEAN,
  ls2 BOOLEAN,
  ls3 BOOLEAN,
  ls4 BOOLEAN,
  ls5 BOOLEAN,
  ls7 BOOLEAN,
  ls8 BOOLEAN,
  lt4 BOOLEAN,
  lt5 BOOLEAN,
  mh5 BOOLEAN,
  ms1 BOOLEAN,
  oh1 BOOLEAN,
  oh3 BOOLEAN,
  rc1 BOOLEAN,
  rg1 BOOLEAN,
  rg2 BOOLEAN,
  rg3 BOOLEAN,
  rg4 BOOLEAN,
  rg5 BOOLEAN,
  rg6 BOOLEAN,
  rg7 BOOLEAN,
  rn2 BOOLEAN,
  rp1 BOOLEAN,
  rp2 BOOLEAN,
  rp3 BOOLEAN,
  rp4 BOOLEAN,
  rp5 BOOLEAN,
  rp6 BOOLEAN,
  rp7 BOOLEAN,
  rp8 BOOLEAN,
  str BOOLEAN, -- Really?
  tc1 BOOLEAN,
  tc2 BOOLEAN,
  tc5 BOOLEAN,
  tc6 BOOLEAN,
  tc9 BOOLEAN,
  tk1 BOOLEAN,
  tk4 BOOLEAN,
  tk6 BOOLEAN,
 
  UNIQUE(property_number)
);
